### ISSUE TITLE
baseboxd exception with GLOG_v=5 caused by initial netlink message

### ISSUE THREAD

**Issue by akoepsel** [bisdn/basebox#305]
## Expected Behavior
baseboxd should not crash ...

## Actual Behavior
An exception occurs when starting baseboxd with an increased logging verbosity level (GLOG_v >= 4), once the first netlink message is received from the underlying subsystems (kernel => netlink => libnl). The netlink message announces the loopback interface and causes the following exception:

```
I0604 14:07:31.449709    13 cnetlink.cc:578] handle_read_event: thread=cthread, tid: 139958419461888, num: 1, name: netlink 
timers list is EMPTY
, fd=6
I0604 14:07:31.449949    13 cnetlink.cc:626] : cache=0x564db0178170, diff=2 action=5 old_obj=0x564db01a78c0 new_obj=0x7f4a94034d40
I0604 14:07:31.450075    13 nl_obj.cc:77] incremented refcounts nl_obj=0x564db01799b0 (old_obj=0x564db01a78c0 new_obj=0x7f4a94034d40)
I0604 14:07:31.450120    13 nl_obj.cc:13] created nl_obj=0x564db01799b0 (old_obj=0x564db01a78c0 new_obj=0x7f4a94034d40)
I0604 14:07:31.450181    13 cnetlink.cc:582] handle_read_event: #processed=1
I0604 14:07:31.450318    13 nl_l3.cc:116] operator() : found configured loopback (nl_obj=0x564db01abd30) 127.0.0.1/8 inet dev lo scope host <permanent>
   label lo
   valid-lifetime forever preferred-lifetime forever
   created boot-time+1s 680msec last-updated boot-time+1s 680msec
I0604 14:07:31.450544    13 nl_bond.cc:35] get_lag_id: lag_id not found for if=1
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 2 "netlink" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f4a9be01700 (LWP 13)]
0x0000564dae125367 in std::char_traits<char>::length (__s=0x0) at /usr/include/c++/9/bits/char_traits.h:335
335             return __builtin_strlen(__s);
(gdb) bt
#0  0x0000564dae125367 in std::char_traits<char>::length (__s=0x0)
    at /usr/include/c++/9/bits/char_traits.h:335
#1  0x0000564dae293e84 in std::basic_string_view<char, std::char_traits<char> >::basic_string_view (this=0x7f4a9be003c0, __str=0x0)
    at /usr/include/c++/9/string_view:124
#2  0x0000564dae2a2c15 in basebox::get_link_type (link=0x564db0197a30)
    at ../src/netlink/netlink-utils.cc:70
#3  0x0000564dae2df620 in basebox::nl_vlan::get_vid (this=0x564db0174ff0, 
    link=0x564db0197a30) at ../src/netlink/nl_vlan.cc:322
#4  0x0000564dae2bc61d in basebox::nl_l3::add_l3_addr (this=0x564db0198a70, 
    a=0x564db01abd30) at ../src/netlink/nl_l3.cc:175
#5  0x0000564dae2bc1fd in basebox::nl_l3::init (this=0x564db0198a70)
    at ../src/netlink/nl_l3.cc:125
#6  0x0000564dae2870ce in basebox::cnetlink::init_subsystems (
    this=0x564db017a970) at ../src/netlink/cnetlink.cc:204
#7  0x0000564dae288fc2 in basebox::cnetlink::handle_wakeup (
    this=0x564db017a970, thread=...) at ../src/netlink/cnetlink.cc:506
#8  0x00007f4a9cfec374 in rofl::cthread::handle_wakeup (this=0x564db017a980)
    at /git/rofl-common/src/rofl/common/locking.hpp:47
#9  0x00007f4a9cfed095 in rofl::cthread::run_loop (this=0x564db017a980)
    at cthread.cpp:732
#10 0x00007f4a9c815609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
--Type <RET> for more, q to quit, c to continue without paging--c
#11 0x00007f4a9c73a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

## Analysis
Refer to line 70 in [src/netlink/netlink-utils.cc](https://github.com/bisdn/basebox/blob/master/src/netlink/netlink-utils.cc#L70) and to function call  rtnl_link_get_family() which is causing the exception due to a NULL pointer in  std::char_traits<char>::length().

There is a test for detecting the loopback device lin [line 74](https://github.com/bisdn/basebox/blob/master/src/netlink/netlink-utils.cc#L74), so swapping the test and the actual logging may solve the issue.

## Steps to Reproduce the Problem
  -  Start baseboxd with GLOG_v=5.
  -  Do not connect any switches.
  -  Wait for the first netlink messages to arrive.

## Specifications
  - Version: baseboxd 1.9.5
  - Platform:
  - Subsystem:

**Comment by akoepsel** [comment]
See proposed fix in this [branch](https://github.com/bisdn/basebox/tree/issue305-baseboxd-exception-caused-by-initial-netlink-message).

**Comment by KanjiMonster** [comment]
Fixed with https://github.com/bisdn/basebox/commit/c2060bfa2918bde71d30356235cee16267d611a8
